export const DOUYIN_URL = "https://v.douyin.com/yTifRziOV1M/";

const yt = (id) => `https://youtu.be/${id}`;
const bili = (id) => `https://www.bilibili.com/video/${id}/`;

export const PARTNER_BRANDS = [
  { slug: "sony", name: "SONY", className: "sony" },
  { slug: "dji", name: "DJI", className: "dji" },
  { slug: "insta360", name: "Insta360", className: "insta" },
  { slug: "tumi", name: "TUMI", className: "tumi" },
  { slug: "bellroy", name: "Bellroy", className: "bellroy" },
  { slug: "xiaoyuzhou", name: "小宇宙", className: "xiaoyuzhou" },
  { slug: "steelcase", name: "Steelcase", className: "steelcase" },
  { slug: "boox", name: "BOOX 文石", className: "boox" },
  { slug: "ef", name: "EF", className: "ef" },
  { slug: "italki", name: "italki", className: "italki" },
  { slug: "moft", name: "MOFT", className: "moft" },
];

export const PARTNER_CASES = [
  {
    id: "sony-iceland",
    brand: "sony",
    title: "我们去冰岛吧！",
    kind: { zh: "旅行叙事", en: "Travel story" },
    youtube: yt("sX7Iv5TgIrk"),
    youtubeId: "sX7Iv5TgIrk",
    bilibili: bili("BV1jy421h7eG"),
  },
  {
    id: "sony-g-master",
    brand: "sony",
    title: "《影·途》：探索者的成长旅程｜Sony G Master",
    kind: { zh: "剧情化品牌短片", en: "Cinematic brand story" },
    youtube: yt("z06c1CMlsTs"),
    youtubeId: "z06c1CMlsTs",
    bilibili: bili("BV1Yu4y167Kd"),
  },

  {
    id: "dji-vlogging-kit",
    brand: "dji",
    title: "我的极简主义 Vlog 套装｜DJI Pocket 3 + DJI Mic 2",
    kind: { zh: "长期使用体验", en: "Long-term review" },
    youtube: yt("VR_0VypTe5Y"),
    youtubeId: "VR_0VypTe5Y",
    bilibili: bili("BV1Z74y127RP"),
  },
  {
    id: "dji-making-video",
    brand: "dji",
    title: "如何制作一支视频",
    kind: { zh: "创作流程", en: "Creator workflow" },
    youtube: yt("JgqT3dq5PSs"),
    youtubeId: "JgqT3dq5PSs",
    bilibili: bili("BV1Gd4y1R7NP"),
  },
  {
    id: "dji-romo-launch",
    brand: "dji",
    title: "大疆，现在连我的家务都包了！",
    kind: { zh: "生活场景植入", en: "Lifestyle integration" },
    youtube: yt("ZIIqtYAdVSg"),
    youtubeId: "ZIIqtYAdVSg",
    bilibili: bili("BV1TgtMzdEhJ"),
  },
  {
    id: "dji-mic-mini",
    brand: "dji",
    title: "大疆迷你麦克风，到底香不香？",
    kind: { zh: "深度评测", en: "In-depth review" },
    youtube: yt("Vm87E7Y_WYg"),
    youtubeId: "Vm87E7Y_WYg",
    bilibili: bili("BV1moBeYjErm"),
  },
  {
    id: "dji-action-comparison",
    brand: "dji",
    title: "DJI Action 4 还是 GoPro 12？看完就会选",
    kind: { zh: "对比评测", en: "Comparison review" },
    youtube: yt("hjdVFuKKtaI"),
    youtubeId: "hjdVFuKKtaI",
    bilibili: bili("BV1HH4y1z7YU"),
  },
  {
    id: "dji-mini4-alshan",
    brand: "dji",
    title: "爱在阿尔山｜DJI Mini 4 Pro 初体验",
    kind: { zh: "旅行故事", en: "Travel story" },
    youtube: yt("U7sOQTJzoCc"),
    youtubeId: "U7sOQTJzoCc",
    bilibili: bili("BV1WN411n7T2"),
  },
  {
    id: "dji-action-qiandaohu",
    brand: "dji",
    title: "千岛湖：骑行爱好者的天堂｜DJI Action 4",
    kind: { zh: "户外实测", en: "Field test" },
    youtube: yt("abnulxTa8wU"),
    youtubeId: "abnulxTa8wU",
    bilibili: bili("BV1jN411H739"),
  },
  {
    id: "dji-air3-creator",
    brand: "dji",
    title: "要做全职创作者，我都做了哪些准备？｜DJI Air 3",
    kind: { zh: "创作者故事", en: "Creator story" },
    youtube: yt("Vo8nWQ--qg4"),
    youtubeId: "Vo8nWQ--qg4",
    bilibili: bili("BV1o841197DB"),
  },
  {
    id: "dji-drone-guide",
    brand: "dji",
    title: "新手无人机到底该怎么选？Mini 3 Pro VS Air 2",
    kind: { zh: "选购指南", en: "Buying guide" },
    youtube: yt("Gk8j438cgT8"),
    youtubeId: "Gk8j438cgT8",
    bilibili: bili("BV1KN4y1G7Kr"),
  },
  {
    id: "dji-romo-150-days",
    brand: "dji",
    title: "DJI ROMO P 150 天长期使用体验",
    kind: { zh: "长期使用体验", en: "150-day review" },
    youtube: yt("QURD-v7n2MI"),
    youtubeId: "QURD-v7n2MI",
    bilibili: bili("BV1WDsBzFE3x"),
  },
  {
    id: "dji-romo-hidden",
    brand: "dji",
    title: "我发现了我家扫地机的 7 个隐藏功能",
    kind: { zh: "真实使用场景", en: "Real-life product use" },
    youtube: yt("8cmkBZHEKe0"),
    youtubeId: "8cmkBZHEKe0",
    bilibili: bili("BV1kfeRzcEt3"),
  },
  {
    id: "dji-mini3-reasons",
    brand: "dji",
    title: "随身携带无人机的 7 个理由｜DJI Mini 3",
    kind: { zh: "生活方式内容", en: "Lifestyle story" },
    bilibili: bili("BV1QY4y1R7gt"),
  },
  {
    id: "dji-mini3-pro",
    brand: "dji",
    title: "DJI Mini 3 Pro 正合我的胃口！",
    kind: { zh: "新手体验", en: "First-time experience" },
    youtube: yt("Theq_PUYeho"),
    youtubeId: "Theq_PUYeho",
    bilibili: bili("BV1NU4y1m7jT"),
  },
  {
    id: "dji-action2-triathlon",
    brand: "dji",
    title: "世界上第一台参加铁人三项的运动相机｜DJI Action 2",
    kind: { zh: "极限场景实测", en: "Endurance field test" },
    youtube: yt("ohwVQx2J6Zk"),
    youtubeId: "ohwVQx2J6Zk",
    bilibili: bili("BV15U4y1u7Bh"),
  },

  {
    id: "insta360-go3",
    brand: "insta360",
    title: "成为博主 900 天，它改变了我对 Vlog 的看法｜Insta360 GO 3",
    kind: { zh: "创作者故事", en: "Creator story" },
    youtube: yt("4o2Qo8soMa0"),
    youtubeId: "4o2Qo8soMa0",
    bilibili: bili("BV1MN4y1Q78R"),
  },
  {
    id: "insta360-eyes",
    brand: "insta360",
    title: "给你这双「眼」，你会看什么？｜Insta360 ONE RS",
    kind: { zh: "创意概念短片", en: "Concept-led product film" },
    youtube: yt("JqU5jhHNuBs"),
    youtubeId: "JqU5jhHNuBs",
    bilibili: bili("BV1ev4y1u7MJ"),
  },

  {
    id: "tumi-investment",
    brand: "tumi",
    title: "这可能是我做过的最值得的投资之一",
    kind: { zh: "旅行生活方式", en: "Travel lifestyle" },
    youtube: yt("V1FZu38QGEQ"),
    youtubeId: "V1FZu38QGEQ",
    bilibili: bili("BV1tyjCzFEp4"),
  },

  {
    id: "bellroy-travel-system",
    brand: "bellroy",
    title: "我的极简主义旅行系统",
    kind: { zh: "旅行装备系统", en: "Travel system" },
    youtube: yt("aqxLEYAf8Xo"),
    youtubeId: "aqxLEYAf8Xo",
    bilibili: bili("BV1urKozVEh8"),
  },
  {
    id: "bellroy-life-update",
    brand: "bellroy",
    title: "同龄人都在往前走，只有我「停滞不前」？",
    kind: { zh: "生活故事植入", en: "Story-led integration" },
    youtube: yt("lvIPgEg85AY"),
    youtubeId: "lvIPgEg85AY",
    bilibili: bili("BV16s596dEJZ"),
  },
  {
    id: "bellroy-edc",
    brand: "bellroy",
    title: "常旅行者随身 EDC 分享｜每年旅行 100 天+",
    kind: { zh: "真实装备分享", en: "Everyday carry" },
    bilibili: bili("BV1BG411C7mt"),
  },
  {
    id: "bellroy-commute",
    brand: "bellroy",
    title: "我的极简通勤背包｜关于时尚你不知道的秘密",
    kind: { zh: "生活方式内容", en: "Lifestyle story" },
    youtube: yt("WpdXr-yWq9E"),
    youtubeId: "WpdXr-yWq9E",
    bilibili: bili("BV1pQ4y1z7mF"),
  },

  {
    id: "xiaoyuzhou-ai",
    brand: "xiaoyuzhou",
    title: "我最近突然对 AI 上头了",
    kind: { zh: "播客合作", en: "Podcast partnership" },
    youtube: yt("7BbZyhZC5kc"),
    youtubeId: "7BbZyhZC5kc",
    bilibili: bili("BV1LuMw6WEDu"),
  },

  {
    id: "steelcase-posture",
    brand: "steelcase",
    title: "99% 的人都坐错了？简单 5 步拯救你的腰",
    kind: { zh: "问题解决型内容", en: "Problem-led education" },
    youtube: yt("6hw_2wqvwMY"),
    youtubeId: "6hw_2wqvwMY",
    bilibili: bili("BV1k5TJzFEZD"),
  },

  {
    id: "boox-four-hours",
    brand: "boox",
    title: "你最值钱的 4 小时，被免费送给了谁？",
    kind: { zh: "效率议题植入", en: "Productivity story" },
    youtube: yt("1wVmvxkqMr8"),
    youtubeId: "1wVmvxkqMr8",
    bilibili: bili("BV1dfM76NERC"),
  },

  {
    id: "ef-investment",
    brand: "ef",
    title: "折腾了 20 年，我才明白普通人最该投的是什么",
    kind: { zh: "教育主题内容", en: "Education story" },
    bilibili: bili("BV15kBYB7Esf"),
  },

  {
    id: "italki-five-steps",
    brand: "italki",
    title: "一个人把英语说得很流利的 5 个方法",
    kind: { zh: "方法型内容", en: "Educational integration" },
    youtube: yt("7WumcemZZzg"),
    youtubeId: "7WumcemZZzg",
    bilibili: bili("BV1WykfB1EcX"),
  },
  {
    id: "italki-relearn-english",
    brand: "italki",
    title: "如果让我重新学英语，我一定不会这样学",
    kind: { zh: "经验型内容", en: "Experience-led education" },
    youtube: yt("PbRQ02tRA10"),
    youtubeId: "PbRQ02tRA10",
    bilibili: bili("BV1sSQnBcEhn"),
  },

  {
    id: "moft-productivity",
    brand: "moft",
    title: "我的极简主义效率系统｜66 天习惯挑战",
    kind: { zh: "效率系统", en: "Productivity system" },
    youtube: yt("tTv1OgJrWEA"),
    youtubeId: "tTv1OgJrWEA",
    bilibili: bili("BV1S2SsYHEQo"),
  },
  {
    id: "moft-slash-life",
    brand: "moft",
    title: "开启我斜杠人生的极简好物",
    kind: { zh: "场景化产品故事", en: "Product-led life story" },
    youtube: yt("EmdU-GBWNf4"),
    youtubeId: "EmdU-GBWNf4",
    bilibili: bili("BV17H4y1B7fN"),
  },
];

export const FEATURED_CASE_IDS = [
  "sony-g-master",
  "dji-vlogging-kit",
  "dji-romo-hidden",
  "insta360-go3",
  "tumi-investment",
  "bellroy-travel-system",
];

export const getBrand = (slug) => PARTNER_BRANDS.find((brand) => brand.slug === slug);
export const getBrandCases = (slug) => PARTNER_CASES.filter((item) => item.brand === slug);
export const getFeaturedCases = () => FEATURED_CASE_IDS.map((id) => PARTNER_CASES.find((item) => item.id === id)).filter(Boolean);
